-- Generated by protobuf; do not edit
local module = {}
local protobuf = require "protobuf.protobuf"

module.HEADER = protobuf.Descriptor()
module.HEADER_CMD_FIELD = protobuf.FieldDescriptor()
module.HEADER_SEQ_FIELD = protobuf.FieldDescriptor()

module.HEADER_CMD_FIELD.name = "cmd"
module.HEADER_CMD_FIELD.full_name = ".Header.cmd"
module.HEADER_CMD_FIELD.number = 1
module.HEADER_CMD_FIELD.index = 0
module.HEADER_CMD_FIELD.label = 1
module.HEADER_CMD_FIELD.has_default_value = false
module.HEADER_CMD_FIELD.default_value = 0
module.HEADER_CMD_FIELD.type = 3
module.HEADER_CMD_FIELD.cpp_type = 2

module.HEADER_SEQ_FIELD.name = "seq"
module.HEADER_SEQ_FIELD.full_name = ".Header.seq"
module.HEADER_SEQ_FIELD.number = 2
module.HEADER_SEQ_FIELD.index = 1
module.HEADER_SEQ_FIELD.label = 1
module.HEADER_SEQ_FIELD.has_default_value = false
module.HEADER_SEQ_FIELD.default_value = 0
module.HEADER_SEQ_FIELD.type = 5
module.HEADER_SEQ_FIELD.cpp_type = 1

module.HEADER.name = "Header"
module.HEADER.full_name = ".Header"
module.HEADER.nested_types = {}
module.HEADER.enum_types = {}
module.HEADER.fields = {module.HEADER_CMD_FIELD, module.HEADER_SEQ_FIELD}
module.HEADER.is_extendable = false
module.HEADER.extensions = {}

module.Header = protobuf.Message(module.HEADER)

module.MESSAGE_TYPES = {"Header"}
module.ENUM_TYPES = {}

return module
