-- Generated by protobuf; do not edit
local module = {}
local protobuf = require "protobuf.protobuf"
local common_pb2 = require "common_pb2"

module.PERSON = protobuf.Descriptor()
module.PERSON_HEADER_FIELD = protobuf.FieldDescriptor()
module.PERSON_ID_FIELD = protobuf.FieldDescriptor()
module.PERSON_NAME_FIELD = protobuf.FieldDescriptor()
module.PERSON_AGE_FIELD = protobuf.FieldDescriptor()
module.PERSON_EMAIL_FIELD = protobuf.FieldDescriptor()
module.PERSON_ARRAY_FIELD = protobuf.FieldDescriptor()
module.PERSON_PHONE_FIELD = protobuf.FieldDescriptor()
module.PHONE = protobuf.Descriptor()
module.PHONE_PHONE_TYPE = protobuf.EnumDescriptor()
module.PHONE_PHONE_TYPE_MOBILE_ENUM = protobuf.EnumValueDescriptor()
module.PHONE_PHONE_TYPE_HOME_ENUM = protobuf.EnumValueDescriptor()
module.PHONE_NUM_FIELD = protobuf.FieldDescriptor()
module.PHONE_TYPE_FIELD = protobuf.FieldDescriptor()

module.PERSON_HEADER_FIELD.name = "header"
module.PERSON_HEADER_FIELD.full_name = ".Person.header"
module.PERSON_HEADER_FIELD.number = 1
module.PERSON_HEADER_FIELD.index = 0
module.PERSON_HEADER_FIELD.label = 1
module.PERSON_HEADER_FIELD.has_default_value = false
module.PERSON_HEADER_FIELD.default_value = nil
module.PERSON_HEADER_FIELD.message_type = common_pb2.Header
module.PERSON_HEADER_FIELD.type = 11
module.PERSON_HEADER_FIELD.cpp_type = 10

module.PERSON_ID_FIELD.name = "id"
module.PERSON_ID_FIELD.full_name = ".Person.id"
module.PERSON_ID_FIELD.number = 2
module.PERSON_ID_FIELD.index = 1
module.PERSON_ID_FIELD.label = 1
module.PERSON_ID_FIELD.has_default_value = false
module.PERSON_ID_FIELD.default_value = 0
module.PERSON_ID_FIELD.type = 3
module.PERSON_ID_FIELD.cpp_type = 2

module.PERSON_NAME_FIELD.name = "name"
module.PERSON_NAME_FIELD.full_name = ".Person.name"
module.PERSON_NAME_FIELD.number = 3
module.PERSON_NAME_FIELD.index = 2
module.PERSON_NAME_FIELD.label = 1
module.PERSON_NAME_FIELD.has_default_value = false
module.PERSON_NAME_FIELD.default_value = ""
module.PERSON_NAME_FIELD.type = 9
module.PERSON_NAME_FIELD.cpp_type = 9

module.PERSON_AGE_FIELD.name = "age"
module.PERSON_AGE_FIELD.full_name = ".Person.age"
module.PERSON_AGE_FIELD.number = 4
module.PERSON_AGE_FIELD.index = 3
module.PERSON_AGE_FIELD.label = 1
module.PERSON_AGE_FIELD.has_default_value = false
module.PERSON_AGE_FIELD.default_value = 0
module.PERSON_AGE_FIELD.type = 5
module.PERSON_AGE_FIELD.cpp_type = 1

module.PERSON_EMAIL_FIELD.name = "email"
module.PERSON_EMAIL_FIELD.full_name = ".Person.email"
module.PERSON_EMAIL_FIELD.number = 5
module.PERSON_EMAIL_FIELD.index = 4
module.PERSON_EMAIL_FIELD.label = 1
module.PERSON_EMAIL_FIELD.has_default_value = false
module.PERSON_EMAIL_FIELD.default_value = ""
module.PERSON_EMAIL_FIELD.type = 9
module.PERSON_EMAIL_FIELD.cpp_type = 9

module.PERSON_ARRAY_FIELD.name = "array"
module.PERSON_ARRAY_FIELD.full_name = ".Person.array"
module.PERSON_ARRAY_FIELD.number = 6
module.PERSON_ARRAY_FIELD.index = 5
module.PERSON_ARRAY_FIELD.label = 1
module.PERSON_ARRAY_FIELD.has_default_value = false
module.PERSON_ARRAY_FIELD.default_value = 0
module.PERSON_ARRAY_FIELD.type = 5
module.PERSON_ARRAY_FIELD.cpp_type = 1

module.PERSON_PHONE_FIELD.name = "phone"
module.PERSON_PHONE_FIELD.full_name = ".Person.phone"
module.PERSON_PHONE_FIELD.number = 7
module.PERSON_PHONE_FIELD.index = 6
module.PERSON_PHONE_FIELD.label = 1
module.PERSON_PHONE_FIELD.has_default_value = false
module.PERSON_PHONE_FIELD.default_value = nil
module.PERSON_PHONE_FIELD.message_type = Phone
module.PERSON_PHONE_FIELD.type = 11
module.PERSON_PHONE_FIELD.cpp_type = 10

module.PERSON.name = "Person"
module.PERSON.full_name = ".Person"
module.PERSON.nested_types = {}
module.PERSON.enum_types = {}
module.PERSON.fields = {
    module.PERSON_HEADER_FIELD,
    module.PERSON_ID_FIELD,
    module.PERSON_NAME_FIELD,
    module.PERSON_AGE_FIELD,
    module.PERSON_EMAIL_FIELD,
    module.PERSON_ARRAY_FIELD,
    module.PERSON_PHONE_FIELD
}
module.PERSON.is_extendable = false
module.PERSON.extensions = {}
module.PHONE_PHONE_TYPE_MOBILE_ENUM.name = "MOBILE"
module.PHONE_PHONE_TYPE_MOBILE_ENUM.index = 0
module.PHONE_PHONE_TYPE_MOBILE_ENUM.number = 0
module.PHONE_PHONE_TYPE_HOME_ENUM.name = "HOME"
module.PHONE_PHONE_TYPE_HOME_ENUM.index = 1
module.PHONE_PHONE_TYPE_HOME_ENUM.number = 1
module.PHONE_PHONE_TYPE.name = "PHONE_TYPE"
module.PHONE_PHONE_TYPE.full_name = ".Phone.PHONE_TYPE"
module.PHONE_PHONE_TYPE.values = {PHONE_PHONE_TYPE_MOBILE_ENUM, PHONE_PHONE_TYPE_HOME_ENUM}
module.PHONE_NUM_FIELD.name = "num"
module.PHONE_NUM_FIELD.full_name = ".Phone.num"
module.PHONE_NUM_FIELD.number = 1
module.PHONE_NUM_FIELD.index = 0
module.PHONE_NUM_FIELD.label = 1
module.PHONE_NUM_FIELD.has_default_value = false
module.PHONE_NUM_FIELD.default_value = ""
module.PHONE_NUM_FIELD.type = 9
module.PHONE_NUM_FIELD.cpp_type = 9

module.PHONE_TYPE_FIELD.name = "type"
module.PHONE_TYPE_FIELD.full_name = ".Phone.type"
module.PHONE_TYPE_FIELD.number = 2
module.PHONE_TYPE_FIELD.index = 1
module.PHONE_TYPE_FIELD.label = 1
module.PHONE_TYPE_FIELD.has_default_value = false
module.PHONE_TYPE_FIELD.default_value = nil
module.PHONE_TYPE_FIELD.enum_type = module.PHONE_TYPE
module.PHONE_TYPE_FIELD.type = 14
module.PHONE_TYPE_FIELD.cpp_type = 8

module.PHONE.name = "Phone"
module.PHONE.full_name = ".Phone"
module.PHONE.nested_types = {}
module.PHONE.enum_types = {module.PHONE_PHONE_TYPE}
module.PHONE.fields = {module.PHONE_NUM_FIELD, module.PHONE_TYPE_FIELD}
module.PHONE.is_extendable = false
module.PHONE.extensions = {}

module.Person = protobuf.Message(module.PERSON)
module.Phone = protobuf.Message(module.PHONE)

module.MESSAGE_TYPES = {"Person", "Phone"}
module.ENUM_TYPES = {}

return module
